### ISSUE TITLE
Unable to build native image

### ISSUE THREAD

**Issue by danipenaperez** [quarkiverse/quarkiverse-google-cloud-services#37]
Hi guys! I am having this error while building native image:
Error: substitution target for io.quarkiverse.googlecloudservices.common.runtime.graal.DefaultHttpTransportFactorySubstitution is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: substitution target for io.quarkiverse.googlecloudservices.common.runtime.graal.DefaultHttpTransportFactorySubstitution is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:834)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:252)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:908)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:838)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------

I am using graalvm Running Quarkus native-image plugin on GraalVM Version 20.1.0 (Java Version 11.0.7), trying to compile the example Pubsub at https://github.com/quarkiverse/quarkiverse-google-cloud-services/tree/master/pubsub
quarkus 1.9.1.Final

thanks in advance

**Comment by loicmathieu** [comment]
I didn't tested this library with Quarkus 1.9.1 yet and it may not be compatible.
Can you try to downgrade to Quarkus 1.8.3 and see if it fixes the issue ?

**Comment by loicmathieu** [comment]
Also, Quarkus uses now GraalVM 20.2 as a base version, can you try with this one please?

**Comment by danipenaperez** [comment]
Hi Loic! downgraded to 1.8.3 still the same issue . I made this repo https://github.com/danipenaperez/issue-quarkus-google-pubsub  to easily reproduce  (clone and master branch)
I run with graal 20.2.0 in this way
./mvnw package -Pnative -Dquarkus.native.container-build=true
I am going to try with older graalvm versions instead

**Comment by danipenaperez** [comment]
I am not lucky with older versions. GraalVM upgrade is a must.

[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.IllegalStateException: Out of date version of GraalVM detected: GraalVM Version 19.3.2 CE. Quarkus currently supports 20.2. Please upgrade GraalVM to this version.
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.checkGraalVMVersion(NativeImageBuildStep.java:528)

**Comment by loicmathieu** [comment]
I saw you're using version 0.2.0-SNAPSHOT. So you build it by yourself ?
Can you try with the release version of the library: `0.1.2` instead ?

**Comment by danipenaperez** [comment]
yes I build in by source code directly , because building with :
mvn io.quarkus:quarkus-maven-plugin:1.8.3.Final:create -DprojectGroupId=org.acme  -DprojectArtifactId=pubsub-quickstart-dpp  -Dextensions="quarkus-google-cloud-pubsub"  
throw me an error 
Cannot find a dependency matching 'quarkus-google-cloud-pubsub', maybe a typo?
[ERROR] Unable to install the Maven wrapper (./mvnw) in the project
org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-readable POM ..... (No found file) 

Lets to try with 0.1.2 , but the same issue "...Error: substitution target..."

I updated the repo if you want to reproduce the behaviour

**Comment by danipenaperez** [comment]
So, when I tried with ./mvnw quarkus:add-extension -Dextensions="quarkus-google-cloud-pubsub" , show an error like this
Failed to execute goal io.quarkus:quarkus-maven-plugin:1.8.3.Final:add-extension (default-cli) on project getting-started: Unable to update the pom.xml file: Unable to add extensions -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:1.8.3.Final:add-extension (default-cli) on project getting-started: Unable to update the pom.xml file

So , I downloaded the code and build the extension. Maybe i mistake some maven repository configuration?

**Comment by loicmathieu** [comment]
@danipenaperez I can reproduce the error, this is my first bug thank you very much :) 

This substitution should be needed, but not for pubsub, as my integration test includes all library something else should need it.

**Comment by loicmathieu** [comment]
OK, I find the issue.
A GraalVM substitution on the common module was not needed for pubsub as it didn't rely on the same authentication mechanism that the other libraries.

I'll create a fix and make a new release.

As a workaround you should be able to build a native image of your application by adding the `quarkus-google-cloud-storage` library.

**Comment by danipenaperez** [comment]
> @danipenaperez I can reproduce the error, this is my first bug thank you very much :)
> 
LOL ,  I am sorry @loicmathieu   ;-D . I think you did a nice work for all quarkus community adding google cloud support!!

**Comment by loicmathieu** [comment]
Don't take it wrong, I'm sincerely happy !
This is a challenger!
And this means someone use my library ;)

**Comment by danipenaperez** [comment]
Loic I tried adding cloud-storage dependency and now it works. And I tried with quarkus 1.9.1final and works too. Congrats!!! 
I owe you a beer !!

**Comment by loicmathieu** [comment]
Cool ;)

You can also build master it's based on Quarkus 1.9 and have the fix.
I try to build a release soon if I can.

Don't hesitate to give me feedback on it (you can join me on Quarkus Zulip) or open issue with possible enhancements
